version: '3.4'

services:
  cicd:
    image: gameinpl/beerpoly-ci
    environment:
      TZ: 'Europe/Berlin'
    restart: unless-stopped
    environment:
      - "SLOT_buildBeerpoly_SECRET_1=git:CHANGE_IT_056f32ee5cf49404607e368bd8d3f2af"
      - "SLOT_buildBeerpoly_SECRET_2=bitbucket:CHANGE_IT_4124bc0a9335c27f086f24ba207a4912"
      - "SLOT_buildBeerpoly_SECRET_3=tom:CHANGE_IT_92eb5ffee6ae2fec3ad71c777531578f"
    ports:
      - 5555:5555
